// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUdZotjRWnNRcUjxFu4HaiILS3Lbrd7QU',
    appId: '1:65951969052:web:0dcf37da88c1ff159c94d9',
    messagingSenderId: '65951969052',
    projectId: 'bbc-barbearia',
    authDomain: 'bbc-barbearia.firebaseapp.com',
    storageBucket: 'bbc-barbearia.firebasestorage.app',
    measurementId: 'G-R2GE3F5MD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfYzlWcxoKfVHKsQ3YDTmYw8cdfyIV72A',
    appId: '1:65951969052:android:74c7072dbb7908f79c94d9',
    messagingSenderId: '65951969052',
    projectId: 'bbc-barbearia',
    storageBucket: 'bbc-barbearia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2V2XRWAjJN9MoKnj1S2Z9xdPGCfuVbkg',
    appId: '1:65951969052:ios:81608f795b8a0f3e9c94d9',
    messagingSenderId: '65951969052',
    projectId: 'bbc-barbearia',
    storageBucket: 'bbc-barbearia.firebasestorage.app',
    iosBundleId: 'com.alme.bbcbarbearia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2V2XRWAjJN9MoKnj1S2Z9xdPGCfuVbkg',
    appId: '1:65951969052:ios:81608f795b8a0f3e9c94d9',
    messagingSenderId: '65951969052',
    projectId: 'bbc-barbearia',
    storageBucket: 'bbc-barbearia.firebasestorage.app',
    iosBundleId: 'com.alme.bbcbarbearia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUdZotjRWnNRcUjxFu4HaiILS3Lbrd7QU',
    appId: '1:65951969052:web:0c015eec550a709d9c94d9',
    messagingSenderId: '65951969052',
    projectId: 'bbc-barbearia',
    authDomain: 'bbc-barbearia.firebaseapp.com',
    storageBucket: 'bbc-barbearia.firebasestorage.app',
    measurementId: 'G-M2RXPR34G2',
  );

}